name: Check files on kotlin master branch still match
on:
  schedule:
    - cron: "45 11 * * 4" # Every Thursday at 11:45 (AM). Why is this brainfuck syntax still the main standard??
  workflow_dispatch:
jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./Check-our-files-are-up-to-date.main.kts
        working-directory: "files-changes-check"
